name: build-lint-test

defaults:
  run:
    shell: bash

on:
  pull_request:

env:
  LIB_CURL_IMPERSONATE: "true"

concurrency:
  group: build-lint-test-${{ github.head_ref }}
  cancel-in-progress: true

# all jobs here must have a matrix identical to the ones inside build-and-release.yaml

jobs:
  config:
    uses: ./.github/workflows/reusable-config.yaml

  lint-and-tsc:
    uses: ./.github/workflows/reusable-lint-tsc.yaml

  build-and-test:
    runs-on: ${{ matrix.os == 'alpine' && 'ubuntu-22.04' || matrix.os }}
    container: ${{ matrix.os == 'alpine' && format('node:{0}-alpine3.21', matrix.node) || '' }}
    needs: config
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - alpine
        node:
          - 24
          - 22
        include:
          # we only want to record coverage in one of the jobs, in this case, the one for the latest stable Node.js version
          - os: ubuntu-22.04
            node: 24
            record-coverage: true
    env:
      # these are false because we run tests separately
      PUBLISH_BINARY: false
      RUN_TESTS: false
      RUN_PREGYP_CLEAN: false
      GIT_COMMIT: ${{ github.sha }}
      GIT_REF_NAME: ${{ github.ref_name }}
    steps:
      - name: Install updated git (Alpine)
        if: matrix.os == 'alpine'
        shell: sh
        run: |
          apk add --no-cache git bash

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install System Packages
        uses: ./.github/actions/install-system-packages
    
      # see https://github.com/nodejs/node/issues/40537
      - name: Enforce IPv4 Connectivity
        if: matrix.os != 'alpine'
        uses: ./.github/actions/force-ipv4

      # PNPM / Node.js
      - name: Setup Node and PNPM
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '${{ matrix.node }}'
          skip-node-setup: ${{ matrix.os == 'alpine' && 'true' || 'false' }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: matrix.enable-debugging

      - name: 'Build and Package Binary'
        run: ./scripts/ci/build.sh

      - name: 'Run tests'
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        if: matrix.record-coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**
          fail_ci_if_error: false

      - name: Upload Build Logs
        if: always()
        uses: ./.github/actions/upload-build-logs
        with:
          artifact-name: build-logs-${{ matrix.os }}-node-${{ matrix.node }}
          retention-days: '3'
