name: build-and-release

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      publish-binary:
        type: boolean
        default: false
        description: Force publish binary?
        required: true

env:
  NODE_LIBCURL_GITHUB_TOKEN: ${{ secrets.NODE_LIBCURL_GITHUB_TOKEN }}
  LIB_CURL_IMPERSONATE: 'true'

concurrency:
  group: build-and-release-${{ github.ref_name }}
  cancel-in-progress: true

# all jobs here must have a matrix identical to the ones inside build-and-release.yaml

jobs:
  config:
    uses: ./.github/workflows/reusable-config.yaml

  lint-and-tsc:
    uses: ./.github/workflows/reusable-lint-tsc.yaml

  build-and-release:
    permissions:
      id-token: write
      attestations: write
      contents: write
      packages: write
    runs-on: ${{ matrix.os == 'alpine' && 'ubuntu-22.04' || matrix.os }}
    container: ${{ matrix.os == 'alpine' && format('node:{0}-alpine3.21', matrix.node) || '' }}
    needs:
      - config
      - lint-and-tsc

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - alpine
        node:
          - 24
          - 22
    env:
      # this is false because we publish as a separate step
      PUBLISH_BINARY: false
      GIT_COMMIT: ${{ github.sha }}
      GIT_REF_NAME: ${{ github.ref_name }}
    steps:
      - name: Install initial deps (Alpine)
        if: matrix.os == 'alpine'
        shell: sh
        run: |
          apk add --no-cache git bash

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install System Packages
        uses: ./.github/actions/install-system-packages
  
      - name: Should publish binary?
        id: should-publish
        run: |
          if [ "${{ inputs.publish-binary }}" = "true" ] || [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "result=true" >> "$GITHUB_OUTPUT"
          else
            echo "result=false" >> "$GITHUB_OUTPUT"
          fi

      # see https://github.com/nodejs/node/issues/40537
      - name: Enforce IPv4 Connectivity
        if: matrix.os != 'alpine'
        uses: ./.github/actions/force-ipv4

      # PNPM / Node.js
      - name: Setup Node and PNPM
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '${{ matrix.node }}'
          skip-node-setup: ${{ matrix.os == 'alpine' && 'true' || 'false' }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: matrix.enable-debugging

      - name: 'Build and Package Binary'
        run: ./scripts/ci/build.sh

      - name: Create attestations
        uses: actions/attest-build-provenance@v3
        if: steps.should-publish.outputs.result == 'true'
        with:
          subject-path: 'build/**/node_libcurl-*.tar.gz'

      - name: 'Publish Binary [macos arm64]'
        if: runner.os == 'macOS' && steps.should-publish.outputs.result == 'true'
        env:
          npm_config_target_arch: arm64
        run: |
          node scripts/module-packaging.js --publish "$(pnpm --silent pregyp reveal staged_tarball --silent)"

      - name: 'Publish Binary [macos x64]'
        if: runner.os == 'macOS' && steps.should-publish.outputs.result == 'true'
        env:
          npm_config_target_arch: x64
        run: |
          node scripts/module-packaging.js --publish "$(pnpm --silent pregyp reveal staged_tarball --silent)"

      - name: 'Publish Binary [non macos]'
        if: runner.os != 'macOS' && steps.should-publish.outputs.result == 'true'
        run: |
          node scripts/module-packaging.js --publish "$(pnpm --silent pregyp reveal staged_tarball --silent)"

      - name: Upload Build Logs
        if: always()
        uses: ./.github/actions/upload-build-logs
        with:
          artifact-name: build-logs-${{ matrix.os }}-node-${{ matrix.node }}
          retention-days: '3'
